[mcp_servers.chrome-devtools]
args = [
    "chrome-devtools-mcp@latest",
    "--headless",
    "--isolated",
    "--chromeArg=--no-sandbox",
    "--chromeArg=--disable-setuid-sandbox",
    "--chromeArg=--disable-dev-shm-usage",
]
command = "npx"

[mcp_servers.dart]
args = ["mcp-server"]
command = "dart"
