name: _dartclaw_workspace
publish_to: none

environment:
  sdk: ^3.11.0

workspace:
  - packages/dartclaw
  - packages/dartclaw_models
  - packages/dartclaw_core
  - packages/dartclaw_storage
  - packages/dartclaw_server
  - apps/dartclaw_cli
