name: _dartclaw_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - dev/fitness
  - packages/dartclaw
  - packages/dartclaw_client
  - packages/dartclaw_kernel
  - packages/dartclaw_bridge
  - packages/dartclaw_core
  - packages/dartclaw_acp
  - packages/dartclaw_workflow
  - packages/dartclaw_google_chat
  - packages/dartclaw_whatsapp
  - packages/dartclaw_signal
  - packages/dartclaw_testing
  - packages/dartclaw_runtime
  - apps/dartclaw_cli
