part of '../config_meta.dart';

/// Per-channel fields, including channel-package-private keys.
const Map<String, FieldMeta> _channelFields = {
  'channels.whatsapp.dm_access': FieldMeta(
    yamlPath: 'channels.whatsapp.dm_access',
    jsonKey: 'channels.whatsapp.dmAccess',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Who may open a one-to-one WhatsApp conversation: pairing demands an invite, allowlist checks the listed senders, open accepts anyone, disabled ignores them.',
    allowedValues: ['open', 'disabled', 'allowlist', 'pairing'],
  ),
  'channels.whatsapp.group_access': FieldMeta(
    yamlPath: 'channels.whatsapp.group_access',
    jsonKey: 'channels.whatsapp.groupAccess',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Which WhatsApp groups may reach the agent: allowlist checks the listed groups, open accepts any, disabled ignores them.',
    allowedValues: ['open', 'disabled', 'allowlist'],
  ),
  'channels.whatsapp.require_mention': FieldMeta(
    yamlPath: 'channels.whatsapp.require_mention',
    jsonKey: 'channels.whatsapp.requireMention',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Only act on WhatsApp group messages that name the bot. Off answers every message in the group.',
  ),
  'channels.signal.dm_access': FieldMeta(
    yamlPath: 'channels.signal.dm_access',
    jsonKey: 'channels.signal.dmAccess',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Who may open a one-to-one Signal conversation: pairing demands an invite, allowlist checks the listed senders, open accepts anyone, disabled ignores them.',
    allowedValues: ['open', 'disabled', 'allowlist', 'pairing'],
  ),
  'channels.signal.group_access': FieldMeta(
    yamlPath: 'channels.signal.group_access',
    jsonKey: 'channels.signal.groupAccess',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Which Signal groups may reach the agent: allowlist checks the listed groups, open accepts any, disabled ignores them.',
    allowedValues: ['open', 'disabled', 'allowlist'],
  ),
  'channels.signal.require_mention': FieldMeta(
    yamlPath: 'channels.signal.require_mention',
    jsonKey: 'channels.signal.requireMention',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Only act on Signal group messages that name the bot. Off answers every message in the group.',
  ),
  'channels.google_chat.enabled': FieldMeta(
    yamlPath: 'channels.google_chat.enabled',
    jsonKey: 'channels.googleChat.enabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Run the Google Chat integration. Off leaves its transport unstarted.',
  ),
  'channels.google_chat.service_account': FieldMeta(
    yamlPath: 'channels.google_chat.service_account',
    jsonKey: 'channels.googleChat.serviceAccount',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.readonly,
    description: 'Service-account JSON, or a path to it, used for the Chat REST API. Read-only: secret material is never editable through the API.',
    nullable: true,
  ),
  'channels.google_chat.oauth_credentials': FieldMeta(
    yamlPath: 'channels.google_chat.oauth_credentials',
    jsonKey: 'channels.googleChat.oauthCredentials',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Path to the OAuth client credentials JSON needed by user-auth features such as Workspace Events subscriptions.',
    nullable: true,
  ),
  'channels.google_chat.audience.type': FieldMeta(
    yamlPath: 'channels.google_chat.audience.type',
    jsonKey: 'channels.googleChat.audience.type',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.readonly,
    description:
        'Which audience claim an inbound signed request must carry: the app URL, or the numeric project number.',
    nullable: true,
    allowedValues: ['app-url', 'project-number'],
  ),
  'channels.google_chat.audience.value': FieldMeta(
    yamlPath: 'channels.google_chat.audience.value',
    jsonKey: 'channels.googleChat.audience.value',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.readonly,
    description: 'Expected audience matching the declared form. A request that fails it is rejected before parsing.',
    nullable: true,
  ),
  'channels.google_chat.webhook_path': FieldMeta(
    yamlPath: 'channels.google_chat.webhook_path',
    jsonKey: 'channels.googleChat.webhookPath',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'HTTP path the synchronous Chat webhook is mounted at.',
  ),
  'channels.google_chat.bot_user': FieldMeta(
    yamlPath: 'channels.google_chat.bot_user',
    jsonKey: 'channels.googleChat.botUser',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Chat user resource name of the bot, used to drop its own messages. Null disables self-filtering.',
    nullable: true,
  ),
  'channels.google_chat.typing_indicator': FieldMeta(
    yamlPath: 'channels.google_chat.typing_indicator',
    jsonKey: 'channels.googleChat.typingIndicator',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description:
        'How work in progress is shown: a placeholder message, an emoji reaction, or nothing. A YAML boolean is also '
        'accepted, true meaning the placeholder message.',
    alsoAccepts: ConfigFieldType.bool_,
    allowedValues: ['disabled', 'message', 'emoji', 'true', 'false'],
  ),
  'channels.google_chat.dm_access': FieldMeta(
    yamlPath: 'channels.google_chat.dm_access',
    jsonKey: 'channels.googleChat.dmAccess',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Who may open a one-to-one Google Chat conversation: pairing demands an invite, allowlist checks the listed senders, open accepts anyone, disabled ignores them.',
    allowedValues: ['open', 'disabled', 'allowlist', 'pairing'],
  ),
  'channels.google_chat.dm_allowlist': FieldMeta(
    yamlPath: 'channels.google_chat.dm_allowlist',
    jsonKey: 'channels.googleChat.dmAllowlist',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Approved one-to-one Google Chat senders, used while direct access is allowlist-based.',
    nullable: true,
  ),
  'channels.google_chat.group_access': FieldMeta(
    yamlPath: 'channels.google_chat.group_access',
    jsonKey: 'channels.googleChat.groupAccess',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Which Google Chat groups may reach the agent: allowlist checks the listed groups, open accepts any, disabled ignores them.',
    allowedValues: ['open', 'disabled', 'allowlist'],
  ),
  'channels.google_chat.group_allowlist': FieldMeta(
    yamlPath: 'channels.google_chat.group_allowlist',
    jsonKey: 'channels.googleChat.groupAllowlist',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Approved Google Chat groups, used while group access is allowlist-based. Plain IDs or maps carrying an id plus optional name, project, model and effort.',
    nullable: true,
  ),
  'channels.google_chat.require_mention': FieldMeta(
    yamlPath: 'channels.google_chat.require_mention',
    jsonKey: 'channels.googleChat.requireMention',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Only act on Google Chat group messages that name the bot. Off answers every message in the group.',
  ),
  'channels.google_chat.quote_reply': FieldMeta(
    yamlPath: 'channels.google_chat.quote_reply',
    jsonKey: 'channels.googleChat.quoteReplyMode',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'How a reply attributes the inbound message: none, a text attribution line, or a native quoted bubble that needs user-level auth.',
    allowedValues: ['disabled', 'sender', 'native'],
  ),
  'channels.google_chat.reactions_auth': FieldMeta(
    yamlPath: 'channels.google_chat.reactions_auth',
    jsonKey: 'channels.googleChat.reactionsAuth',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Reactions need user-level OAuth; disabled turns them off entirely.',
    allowedValues: ['disabled', 'user'],
  ),
  'channels.google_chat.pubsub.project_id': FieldMeta(
    yamlPath: 'channels.google_chat.pubsub.project_id',
    jsonKey: 'channels.googleChat.pubsub.projectId',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'GCP project holding the subscription pulled for asynchronous inbound events.',
    nullable: true,
  ),
  'channels.google_chat.pubsub.subscription': FieldMeta(
    yamlPath: 'channels.google_chat.pubsub.subscription',
    jsonKey: 'channels.googleChat.pubsub.subscription',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Name of the subscription pulled for inbound events.',
    nullable: true,
  ),
  'channels.google_chat.pubsub.poll_interval_seconds': FieldMeta(
    yamlPath: 'channels.google_chat.pubsub.poll_interval_seconds',
    jsonKey: 'channels.googleChat.pubsub.pollIntervalSeconds',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Seconds between pulls. A lower value costs more API requests.',
    min: 1,
  ),
  'channels.google_chat.pubsub.max_messages_per_pull': FieldMeta(
    yamlPath: 'channels.google_chat.pubsub.max_messages_per_pull',
    jsonKey: 'channels.googleChat.pubsub.maxMessagesPerPull',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Messages requested per pull, between 1 and 100.',
    min: 1,
    max: 100,
  ),
  'channels.google_chat.space_events.enabled': FieldMeta(
    yamlPath: 'channels.google_chat.space_events.enabled',
    jsonKey: 'channels.googleChat.spaceEvents.enabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Maintain Workspace Events subscriptions. Needs user OAuth plus a topic and subscription.',
  ),
  'channels.google_chat.space_events.pubsub_topic': FieldMeta(
    yamlPath: 'channels.google_chat.space_events.pubsub_topic',
    jsonKey: 'channels.googleChat.spaceEvents.pubsubTopic',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Topic the Workspace Events subscription publishes notifications to.',
    nullable: true,
  ),
  'channels.google_chat.space_events.event_types': FieldMeta(
    yamlPath: 'channels.google_chat.space_events.event_types',
    jsonKey: 'channels.googleChat.spaceEvents.eventTypes',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Event types subscribed to, shorthand or fully qualified. Each needs a matching OAuth scope.',
    nullable: true,
  ),
  'channels.google_chat.space_events.include_resource': FieldMeta(
    yamlPath: 'channels.google_chat.space_events.include_resource',
    jsonKey: 'channels.googleChat.spaceEvents.includeResource',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Ask for the full resource in each notification. Off delivers name-only events, which have a longer subscription lifetime.',
  ),
  'channels.google_chat.feedback.enabled': FieldMeta(
    yamlPath: 'channels.google_chat.feedback.enabled',
    jsonKey: 'channels.googleChat.feedback.enabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Post progress updates while a long turn runs.',
  ),
  'channels.google_chat.feedback.min_feedback_delay': FieldMeta(
    yamlPath: 'channels.google_chat.feedback.min_feedback_delay',
    jsonKey: 'channels.googleChat.feedback.minFeedbackDelay',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Duration such as 5s a turn must run before the first progress update appears.',
  ),
  'channels.google_chat.feedback.status_interval': FieldMeta(
    yamlPath: 'channels.google_chat.feedback.status_interval',
    jsonKey: 'channels.googleChat.feedback.statusInterval',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Duration such as 30s between progress updates once they start.',
  ),
  'channels.google_chat.feedback.status_style': FieldMeta(
    yamlPath: 'channels.google_chat.feedback.status_style',
    jsonKey: 'channels.googleChat.feedback.statusStyle',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Wording of progress updates: creative, minimal, or silent.',
    allowedValues: ['creative', 'minimal', 'silent'],
  ),

  // --- Channels — subsystem-wide defaults ---
  // Open container: `ChannelConfig.fromYaml` loads every map-valued key here
  // that is not one of the three siblings below as a channel definition, so
  // the block cannot be closed against a channel this registry does not know.
  'channels': FieldMeta(
    yamlPath: 'channels',
    jsonKey: 'channels',
    type: ConfigFieldType.objectMap,
    mutability: ConfigMutability.readonly,
    description:
        'Channel integrations keyed by channel name. The built-in channels are declared field by field; any other '
        'map-valued key is loaded as the definition of a channel registered by a deployer. Read-only: an object-valued '
        'field is written wholesale, so a settable container would carry the read-only Google Chat service account and '
        'audience claim past their own refusal. The individual channel fields keep their own tiers.',
    entry: OpaqueEntry(
      reason:
          'A channel outside the built-in set is defined by the package registering it, so its keys are not '
          'declarable here.',
    ),
  ),
  'channels.debounce_window_ms': FieldMeta(
    yamlPath: 'channels.debounce_window_ms',
    jsonKey: 'channels.debounceWindowMs',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Milliseconds inbound messages from one session are coalesced into a single turn. Default 1000; 0 starts a turn per message.',
    min: 0,
  ),
  'channels.max_queue_depth': FieldMeta(
    yamlPath: 'channels.max_queue_depth',
    jsonKey: 'channels.maxQueueDepth',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description:
        'Messages held per session key while a turn is running. Default 100; beyond it, the oldest are dropped.',
    min: 1,
  ),
  'channels.retry_policy.max_attempts': FieldMeta(
    yamlPath: 'channels.retry_policy.max_attempts',
    jsonKey: 'channels.retryPolicy.maxAttempts',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Delivery attempts for one outbound message before it is dead-lettered, for channels that set no policy of their own. Default 3.',
    min: 1,
  ),
  'channels.retry_policy.base_delay_ms': FieldMeta(
    yamlPath: 'channels.retry_policy.base_delay_ms',
    jsonKey: 'channels.retryPolicy.baseDelayMs',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description:
        'Milliseconds of backoff before the first delivery retry, grown and jittered on later attempts. Default 1000.',
    min: 0,
  ),
  'channels.retry_policy.jitter_factor': FieldMeta(
    yamlPath: 'channels.retry_policy.jitter_factor',
    jsonKey: 'channels.retryPolicy.jitterFactor',
    type: ConfigFieldType.double_,
    mutability: ConfigMutability.restart,
    description:
        'Fraction of the backoff randomly added to each delivery retry, spreading a burst of failures apart. '
        '0 retries on a fixed schedule; default 0.2.',
    min: 0,
    max: 1,
  ),

  // --- Channels — WhatsApp ---
  'channels.whatsapp.enabled': FieldMeta(
    yamlPath: 'channels.whatsapp.enabled',
    jsonKey: 'channels.whatsapp.enabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Run the WhatsApp integration. Off leaves the GOWA sidecar unstarted.',
  ),
  'channels.whatsapp.dm_allowlist': FieldMeta(
    yamlPath: 'channels.whatsapp.dm_allowlist',
    jsonKey: 'channels.whatsapp.dmAllowlist',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Approved one-to-one WhatsApp senders, used while direct access is allowlist-based.',
  ),
  'channels.whatsapp.group_allowlist': FieldMeta(
    yamlPath: 'channels.whatsapp.group_allowlist',
    jsonKey: 'channels.whatsapp.groupAllowlist',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Approved WhatsApp groups, used while group access is allowlist-based. Plain JIDs, or maps carrying an id plus optional name, project, model and effort.',
  ),
  'channels.whatsapp.mention_patterns': FieldMeta(
    yamlPath: 'channels.whatsapp.mention_patterns',
    jsonKey: 'channels.whatsapp.mentionPatterns',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Extra regexes counted as naming the bot in a WhatsApp group, on top of the built-in detection.',
  ),
  'channels.whatsapp.response_prefix': FieldMeta(
    yamlPath: 'channels.whatsapp.response_prefix',
    jsonKey: 'channels.whatsapp.responsePrefix',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Template prepended to the first outbound WhatsApp chunk. Understands the {model} and {agent.identity.name} placeholders.',
  ),
  'channels.whatsapp.max_chunk_size': FieldMeta(
    yamlPath: 'channels.whatsapp.max_chunk_size',
    jsonKey: 'channels.whatsapp.maxChunkSize',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Largest outbound WhatsApp chunk in characters, multipart labels included. A longer reply is split. Default 4000.',
    min: 1,
  ),
  'channels.whatsapp.gowa_executable': FieldMeta(
    yamlPath: 'channels.whatsapp.gowa_executable',
    jsonKey: 'channels.whatsapp.gowaExecutable',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Binary name or absolute path of the GOWA sidecar that talks to WhatsApp.',
  ),
  'channels.whatsapp.gowa_host': FieldMeta(
    yamlPath: 'channels.whatsapp.gowa_host',
    jsonKey: 'channels.whatsapp.gowaHost',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Address the GOWA sidecar HTTP API listens on. Default 127.0.0.1.',
  ),
  'channels.whatsapp.gowa_port': FieldMeta(
    yamlPath: 'channels.whatsapp.gowa_port',
    jsonKey: 'channels.whatsapp.gowaPort',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Port the GOWA sidecar HTTP API listens on. Default 3000; an instance already listening there is attached to rather than spawned.',
    min: 1,
    max: 65535,
  ),
  'channels.whatsapp.gowa_db_uri': FieldMeta(
    yamlPath: 'channels.whatsapp.gowa_db_uri',
    jsonKey: 'channels.whatsapp.gowaDbUri',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Connection string giving the GOWA sidecar persistent pairing state. Null keeps its own local store.',
    nullable: true,
  ),

  // --- Channels — Signal ---
  'channels.signal.enabled': FieldMeta(
    yamlPath: 'channels.signal.enabled',
    jsonKey: 'channels.signal.enabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Run the Signal integration. Off leaves the signal-cli daemon unstarted.',
  ),
  'channels.signal.phone_number': FieldMeta(
    yamlPath: 'channels.signal.phone_number',
    jsonKey: 'channels.signal.phoneNumber',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Account number registered with signal-cli, in E.164 form such as +1234567890.',
  ),
  'channels.signal.executable': FieldMeta(
    yamlPath: 'channels.signal.executable',
    jsonKey: 'channels.signal.executable',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Binary name or absolute path of signal-cli.',
  ),
  'channels.signal.host': FieldMeta(
    yamlPath: 'channels.signal.host',
    jsonKey: 'channels.signal.host',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Address the signal-cli daemon listens on. Default 127.0.0.1.',
  ),
  'channels.signal.port': FieldMeta(
    yamlPath: 'channels.signal.port',
    jsonKey: 'channels.signal.port',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Port the signal-cli daemon listens on. Default 8080.',
    min: 1,
    max: 65535,
  ),
  'channels.signal.dm_allowlist': FieldMeta(
    yamlPath: 'channels.signal.dm_allowlist',
    jsonKey: 'channels.signal.dmAllowlist',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Approved one-to-one Signal senders in E.164 form, used while direct access is allowlist-based.',
  ),
  'channels.signal.group_allowlist': FieldMeta(
    yamlPath: 'channels.signal.group_allowlist',
    jsonKey: 'channels.signal.groupAllowlist',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Approved Signal groups by base64 id, used while group access is allowlist-based. Maps carrying an id plus optional name, project, model and effort are also accepted.',
  ),
  'channels.signal.mention_patterns': FieldMeta(
    yamlPath: 'channels.signal.mention_patterns',
    jsonKey: 'channels.signal.mentionPatterns',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Extra regexes counted as naming the bot in a Signal group, on top of the built-in detection.',
  ),
  'channels.signal.max_chunk_size': FieldMeta(
    yamlPath: 'channels.signal.max_chunk_size',
    jsonKey: 'channels.signal.maxChunkSize',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Largest outbound Signal chunk in characters, multipart labels included. A longer reply is split. Default 4000.',
    min: 1,
  ),
  'channels.signal.response_prefix': FieldMeta(
    yamlPath: 'channels.signal.response_prefix',
    jsonKey: 'channels.signal.responsePrefix',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description:
        'Accepted and discarded — Signal applies no outbound prefix. Registered because the shared channel parser '
        'reads the key for every channel, so a config carrying it must still load.',
  ),

  // --- Google Chat: the shared channel keys it parses and discards ---
  // The one reader in `CommonChannelFields` runs for every channel, so these
  // load and warn on a bad value while changing nothing Google Chat does.
  'channels.google_chat.max_chunk_size': FieldMeta(
    yamlPath: 'channels.google_chat.max_chunk_size',
    jsonKey: 'channels.googleChat.maxChunkSize',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description:
        'Accepted and discarded — outbound Google Chat chunking is pinned at 4000 characters. A non-positive value '
        'is still reported at load.',
    min: 1,
  ),
  'channels.google_chat.mention_patterns': FieldMeta(
    yamlPath: 'channels.google_chat.mention_patterns',
    jsonKey: 'channels.googleChat.mentionPatterns',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description:
        'Accepted and discarded — Google Chat recognizes a mention from the platform annotation, not from a regex.',
  ),
  'channels.google_chat.response_prefix': FieldMeta(
    yamlPath: 'channels.google_chat.response_prefix',
    jsonKey: 'channels.googleChat.responsePrefix',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Accepted and discarded — Google Chat applies no outbound prefix.',
  ),
};
