part of '../config_meta.dart';

/// Server, gateway, workflow, logging and other deployment-wide fields.
const Map<String, FieldMeta> _serverFields = {
  'workspace.git_sync.enabled': FieldMeta(
    yamlPath: 'workspace.git_sync.enabled',
    jsonKey: 'workspace.gitSync.enabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.live,
    description: 'Commit workspace changes to the local repository on the git-sync schedule. Off by default.',
  ),
  'workspace.git_sync.push_enabled': FieldMeta(
    yamlPath: 'workspace.git_sync.push_enabled',
    jsonKey: 'workspace.gitSync.pushEnabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.live,
    description: 'Also push those commits to the configured remote. Ignored while git sync itself is off.',
  ),
  'workspace.git_sync.interval_minutes': FieldMeta(
    yamlPath: 'workspace.git_sync.interval_minutes',
    jsonKey: 'workspace.gitSync.intervalMinutes',
    type: ConfigFieldType.int_,
    // Restart for the same structural reason as the heartbeat interval: a job's
    // schedule is fixed at registration and ScheduleService has no live
    // job-definition mutation path.
    mutability: ConfigMutability.restart,
    description:
        'Minutes between workspace git-sync runs. The job owns this schedule; it no longer rides the heartbeat cycle.',
    min: 1,
    max: 1440,
  ),
  'onboarding.expiry_days': FieldMeta(
    yamlPath: 'onboarding.expiry_days',
    jsonKey: 'onboarding.expiryDays',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Days a pairing invitation stays valid. Minimum 1; an expired invite must be re-issued.',
    min: 1,
  ),
  'port': FieldMeta(
    yamlPath: 'port',
    jsonKey: 'port',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'TCP port the HTTP server binds. Default 3333; excluded from hot reload, so a change needs a restart.',
    min: 1,
    max: 65535,
  ),
  'host': FieldMeta(
    yamlPath: 'host',
    jsonKey: 'host',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Interface the HTTP server binds. Default localhost — bind 0.0.0.0 only behind a trusted proxy.',
  ),
  'name': FieldMeta(
    yamlPath: 'name',
    jsonKey: 'name',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Display label for this instance, shown in the web UI and in channel replies.',
  ),
  'base_url': FieldMeta(
    yamlPath: 'base_url',
    jsonKey: 'baseUrl',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Public URL used to build absolute links for pairing, webhooks and notifications. Null falls back to the bound interface and port.',
    nullable: true,
  ),
  'data_dir': FieldMeta(
    yamlPath: 'data_dir',
    jsonKey: 'dataDir',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description:
        'Instance directory holding sessions, the workspace, databases and credential stores. Default ~/.dartclaw.',
  ),
  'source_dir': FieldMeta(
    yamlPath: 'source_dir',
    jsonKey: 'sourceDir',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description:
        'Checkout root used to locate templates and static assets during development. Null uses the embedded copies.',
    nullable: true,
  ),
  'static_dir': FieldMeta(
    yamlPath: 'static_dir',
    jsonKey: 'staticDir',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Directory served at /static. Null resolves under the checkout root, then the embedded copies.',
    nullable: true,
  ),
  'templates_dir': FieldMeta(
    yamlPath: 'templates_dir',
    jsonKey: 'templatesDir',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Directory the Trellis page templates load from. Null resolves under the checkout root, then the embedded copies.',
    nullable: true,
  ),
  'workflow.workspace_dir': FieldMeta(
    yamlPath: 'workflow.workspace_dir',
    jsonKey: 'workflow.workspaceDir',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Operator-owned checkout the workflow steps run in. Null lets DartClaw manage one under the instance directory and refresh its AGENTS.md on upgrade.',
    nullable: true,
  ),
  'workflow.approvals': FieldMeta(
    yamlPath: 'workflow.approvals',
    jsonKey: 'workflow.approvals',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'How far a run advances unattended: manual pauses on stalls and approval steps, auto-on-stall passes stalls only, auto passes both.',
    allowedValues: ['manual', 'auto-on-stall', 'auto'],
  ),
  'workflow.defaults.workflow.provider': FieldMeta(
    yamlPath: 'workflow.defaults.workflow.provider',
    jsonKey: 'workflow.defaults.workflow.provider',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Harness driving workflow-level turns when a step names none. Null inherits the primary lane setting.',
    nullable: true,
  ),
  'workflow.defaults.workflow.model': FieldMeta(
    yamlPath: 'workflow.defaults.workflow.model',
    jsonKey: 'workflow.defaults.workflow.model',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Model for workflow-level turns when a step names none. Accepts provider/model shorthand.',
    nullable: true,
  ),
  'workflow.defaults.workflow.effort': FieldMeta(
    yamlPath: 'workflow.defaults.workflow.effort',
    jsonKey: 'workflow.defaults.workflow.effort',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Reasoning effort for workflow-level steps when a step names none. Null leaves the harness default.',
    nullable: true,
  ),
  'workflow.defaults.planner.provider': FieldMeta(
    yamlPath: 'workflow.defaults.planner.provider',
    jsonKey: 'workflow.defaults.planner.provider',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Harness driving planner-role steps. Null inherits the workflow-role setting.',
    nullable: true,
  ),
  'workflow.defaults.planner.model': FieldMeta(
    yamlPath: 'workflow.defaults.planner.model',
    jsonKey: 'workflow.defaults.planner.model',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Model for planner-role steps. Accepts provider/model shorthand.',
    nullable: true,
  ),
  'workflow.defaults.planner.effort': FieldMeta(
    yamlPath: 'workflow.defaults.planner.effort',
    jsonKey: 'workflow.defaults.planner.effort',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Reasoning effort for planner-role steps. Null inherits the workflow-role setting.',
    nullable: true,
  ),
  'workflow.defaults.executor.provider': FieldMeta(
    yamlPath: 'workflow.defaults.executor.provider',
    jsonKey: 'workflow.defaults.executor.provider',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Harness driving executor-role steps. Null inherits the workflow-role setting.',
    nullable: true,
  ),
  'workflow.defaults.executor.model': FieldMeta(
    yamlPath: 'workflow.defaults.executor.model',
    jsonKey: 'workflow.defaults.executor.model',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Model for executor-role steps. Accepts provider/model shorthand.',
    nullable: true,
  ),
  'workflow.defaults.executor.effort': FieldMeta(
    yamlPath: 'workflow.defaults.executor.effort',
    jsonKey: 'workflow.defaults.executor.effort',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Reasoning effort for executor-role steps. Null inherits the workflow-role setting.',
    nullable: true,
  ),
  'workflow.defaults.reviewer.provider': FieldMeta(
    yamlPath: 'workflow.defaults.reviewer.provider',
    jsonKey: 'workflow.defaults.reviewer.provider',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Harness driving reviewer-role steps. Null inherits the workflow-role setting.',
    nullable: true,
  ),
  'workflow.defaults.reviewer.model': FieldMeta(
    yamlPath: 'workflow.defaults.reviewer.model',
    jsonKey: 'workflow.defaults.reviewer.model',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Model for reviewer-role steps. Accepts provider/model shorthand.',
    nullable: true,
  ),
  'workflow.defaults.reviewer.effort': FieldMeta(
    yamlPath: 'workflow.defaults.reviewer.effort',
    jsonKey: 'workflow.defaults.reviewer.effort',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Reasoning effort for reviewer-role steps. Null inherits the workflow-role setting.',
    nullable: true,
  ),
  'workflow.runtime_artifacts_retention.mode': FieldMeta(
    yamlPath: 'workflow.runtime_artifacts_retention.mode',
    jsonKey: 'workflow.runtimeArtifactsRetention.mode',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description:
        'Whether stale run artifacts are only reported (warn) or actually deleted (enforce) during maintenance.',
    allowedValues: ['warn', 'enforce'],
  ),
  'workflow.runtime_artifacts_retention.prune_after_days': FieldMeta(
    yamlPath: 'workflow.runtime_artifacts_retention.prune_after_days',
    jsonKey: 'workflow.runtimeArtifactsRetention.pruneAfterDays',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Age in days past which run artifacts are pruned. 0 keeps them indefinitely.',
    min: 0,
  ),
  'auth.cookie_secure': FieldMeta(
    yamlPath: 'auth.cookie_secure',
    jsonKey: 'auth.cookieSecure',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Add the Secure attribute to the session cookie. Needed for HTTPS deployments; it breaks sign-in over plain HTTP.',
  ),
  'auth.trusted_proxies': FieldMeta(
    yamlPath: 'auth.trusted_proxies',
    jsonKey: 'auth.trustedProxies',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Addresses whose forwarded-for header is believed when resolving a client IP. Empty believes none.',
    nullable: true,
  ),
  'security.bash_step.env_allowlist': FieldMeta(
    yamlPath: 'security.bash_step.env_allowlist',
    jsonKey: 'security.bashStep.envAllowlist',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Environment variable names a workflow bash step may read, added to the built-in set. Everything else is stripped from its environment.',
  ),
  'security.bash_step.extra_strip_patterns': FieldMeta(
    yamlPath: 'security.bash_step.extra_strip_patterns',
    jsonKey: 'security.bashStep.extraStripPatterns',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.restart,
    description: 'Extra regexes whose matches are removed from bash-step output before the model sees it.',
  ),
  'concurrency.max_parallel_turns': FieldMeta(
    yamlPath: 'concurrency.max_parallel_turns',
    jsonKey: 'concurrency.maxParallelTurns',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.reloadable,
    description:
        'Ceiling on agent turns executing simultaneously across the instance. Raising it multiplies peak token spend.',
    min: 1,
    max: 10,
  ),
  'logging.level': FieldMeta(
    yamlPath: 'logging.level',
    jsonKey: 'logging.level',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Lowest severity written out. FINE includes per-turn detail and is noisy in production.',
    allowedValues: ['FINE', 'INFO', 'WARNING', 'SEVERE'],
  ),
  'logging.format': FieldMeta(
    yamlPath: 'logging.format',
    jsonKey: 'logging.format',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'human is readable in a terminal; json emits line-delimited records for a log shipper.',
    allowedValues: ['human', 'json'],
  ),
  'logging.file': FieldMeta(
    yamlPath: 'logging.file',
    jsonKey: 'logging.file',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Path written in addition to stdout. Null logs to stdout only.',
    nullable: true,
  ),
  'logging.redact_patterns': FieldMeta(
    yamlPath: 'logging.redact_patterns',
    jsonKey: 'logging.redactPatterns',
    type: ConfigFieldType.stringList,
    mutability: ConfigMutability.reloadable,
    description: 'Regexes whose matches are masked before any line is written out.',
    nullable: true,
  ),
  'search.backend': FieldMeta(
    yamlPath: 'search.backend',
    jsonKey: 'search.backend',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'Engine behind memory search: fts5 uses the bundled SQLite index, qmd delegates to a local daemon.',
    allowedValues: ['fts5', 'qmd'],
  ),
  'search.qmd.host': FieldMeta(
    yamlPath: 'search.qmd.host',
    jsonKey: 'search.qmd.host',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Loopback address of the qmd daemon. Only localhost, 127.x.x.x and ::1 are accepted.',
  ),
  'search.qmd.port': FieldMeta(
    yamlPath: 'search.qmd.port',
    jsonKey: 'search.qmd.port',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'TCP port the qmd daemon listens on. Default 8181.',
    min: 1,
    max: 65535,
  ),
  'search.default_depth': FieldMeta(
    yamlPath: 'search.default_depth',
    jsonKey: 'search.defaultDepth',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Effort a query spends when the caller names none: fast, standard or deep.',
  ),
  'usage.budget_warning_tokens': FieldMeta(
    yamlPath: 'usage.budget_warning_tokens',
    jsonKey: 'usage.budgetWarningTokens',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Daily token count that raises a warning banner. Null shows no warning.',
    nullable: true,
    min: 1,
  ),
  'usage.max_file_size_bytes': FieldMeta(
    yamlPath: 'usage.max_file_size_bytes',
    jsonKey: 'usage.maxFileSizeBytes',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Largest upload accepted through the web UI and channels, in bytes.',
    min: 1,
  ),
  'gateway.auth_mode': FieldMeta(
    yamlPath: 'gateway.auth_mode',
    jsonKey: 'gateway.authMode',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.readonly,
    description: 'token demands the bearer credential on every request; none serves the instance unauthenticated. Read-only through the API — change it in YAML.',
    allowedValues: ['token', 'none'],
  ),
  'gateway.token': FieldMeta(
    yamlPath: 'gateway.token',
    jsonKey: 'gateway.token',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.readonly,
    description:
        'Bearer credential accepted by the API and web UI. Generated when omitted, and never editable through the API.',
  ),
  'gateway.mcp_clients': FieldMeta(
    yamlPath: 'gateway.mcp_clients',
    jsonKey: 'gateway.mcpClients',
    type: ConfigFieldType.objectList,
    mutability: ConfigMutability.readonly,
    description: 'Named MCP clients allowed to reach /mcp with their own bearer token, each limited to the context-engine read tools. Read-only through the API, and each token must be a \${VAR} reference. Empty leaves /mcp accepting the gateway token alone.',
    entry: ObjectEntry(
      fields: {
        'name': EntryFieldMeta(
          type: ConfigFieldType.string,
          description: 'Client name. Appears as the audit principal for every tool call the client makes.',
        ),
        'token': EntryFieldMeta(
          type: ConfigFieldType.string,
          description: 'Bearer credential written as a \${VAR} environment reference. A literal value, or a reference resolving to nothing, refuses to start.',
        ),
      },
    ),
  ),
  'gateway.hsts': FieldMeta(
    yamlPath: 'gateway.hsts',
    jsonKey: 'gateway.hsts',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description:
        'Send Strict-Transport-Security on responses. Safe only once the instance is reached over HTTPS everywhere.',
  ),
  'gateway.reload.mode': FieldMeta(
    yamlPath: 'gateway.reload.mode',
    jsonKey: 'gateway.reload.mode',
    type: ConfigFieldType.enum_,
    mutability: ConfigMutability.restart,
    description: 'How a YAML edit reaches the running server: off never, signal on SIGHUP, auto on file change.',
    allowedValues: ['off', 'signal', 'auto'],
  ),
  'gateway.reload.debounce_ms': FieldMeta(
    yamlPath: 'gateway.reload.debounce_ms',
    jsonKey: 'gateway.reload.debounceMs',
    type: ConfigFieldType.int_,
    mutability: ConfigMutability.restart,
    description: 'Milliseconds to wait after a file change before applying it, so an editor writing twice reloads once. Minimum 100.',
    min: 100,
  ),

  // --- Development mode ---
  'dev_mode': FieldMeta(
    yamlPath: 'dev_mode',
    jsonKey: 'devMode',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Serve assets from the checkout instead of the embedded copies and relax caching. Never leave it on in production.',
  ),

  // --- Container isolation ---
  'container.enabled': FieldMeta(
    yamlPath: 'container.enabled',
    jsonKey: 'container.enabled',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.readonly,
    description:
        'Run agent work inside container isolation. Left unset, DartClaw isolates wherever a container runtime is '
        'detected and starts in advisory mode where none is; an explicit true instead fails startup when the host '
        'cannot isolate. POSIX only; off means guards are the whole boundary. Read-only: placement is a '
        'deterministic keep, and clearing it through the API would either strand an explicit container selection at '
        'the next boot or move neutral-profile work onto the host.',
  ),
  'container.image': FieldMeta(
    yamlPath: 'container.image',
    jsonKey: 'container.image',
    type: ConfigFieldType.string,
    mutability: ConfigMutability.restart,
    description: 'Container image agent work is executed in. Default dartclaw-agent:latest.',
  ),

  // --- Workflow cleanup ---
  'workflow.cleanup.delete_remote_branch_on_failure': FieldMeta(
    yamlPath: 'workflow.cleanup.delete_remote_branch_on_failure',
    jsonKey: 'workflow.cleanup.deleteRemoteBranchOnFailure',
    type: ConfigFieldType.bool_,
    mutability: ConfigMutability.restart,
    description: 'Delete the pushed branch when a run fails. Off keeps it for post-mortem inspection.',
  ),

  // --- Search providers (secret-bearing, so read-only like gateway.token) ---
  'search.providers': FieldMeta(
    yamlPath: 'search.providers',
    jsonKey: 'search.providers',
    type: ConfigFieldType.objectMap,
    mutability: ConfigMutability.readonly,
    description:
        'Web-search vendors keyed by provider id; brave and tavily are the recognized ids. Read-only: each entry '
        'carries or names a credential, which is never editable through the API.',
    entry: ObjectEntry(
      fields: {
        'enabled': EntryFieldMeta(
          type: ConfigFieldType.bool_,
          description: 'Whether this vendor may be queried. Required — an entry without it is skipped at load.',
        ),
        'api_key': EntryFieldMeta(
          type: ConfigFieldType.string,
          description: 'Vendor API key, normally an environment reference such as \${BRAVE_API_KEY}. Exactly one of it and credential is required — an entry with neither, or both, is skipped.',
        ),
        'credential': EntryFieldMeta(
          type: ConfigFieldType.string,
          description: 'Name of a credentials.<name> api-key entry to authenticate with, from the config file or the named credential store. Exactly one of it and api_key is required; an unknown name, a github-token entry or a blank value skips the provider.',
          nullable: true,
        ),
      },
    ),
  ),
};
