part of 'service_wiring.dart';

/// Composes the turn manager the rest of the assembly threads through.
///
/// Built before the server because scheduling, the task layer and the restart
/// service all take it, and the server itself is one more consumer.
TurnManager _composeTurns(
  DartclawConfig config,
  _WiringContext ctx,
  StorageWiring storage,
  HarnessWiring harness,
  SecurityWiring security,
) => composeServerTurns(
  sessions: storage.sessions,
  messages: storage.messages,
  worker: harness.harness,
  behavior: harness.behavior,
  executions: harness.executions,
  policyResolver: harness.policyResolver,
  memoryFile: storage.memoryFile,
  kv: storage.kvService,
  guardChain: security.guardChain,
  lockManager: harness.lockManager,
  resetService: harness.resetService,
  contextMonitor: harness.contextMonitor,
  redactor: ctx.messageRedactor,
  selfImprovement: harness.selfImprovement,
  usageTracker: harness.usageTracker,
  eventBus: ctx.eventBus,
  config: config,
);

DartclawServer _composeRuntimeServer(
  DartclawConfig config,
  String resolvedConfigPath,
  _WiringContext ctx,
  StorageWiring storage,
  TaskWiring task,
  HarnessWiring harness,
  SchedulingWiring scheduling,
  ProjectWiring project,
  ProviderStatusService providerStatus,
  WorkflowService workflowService,
  WorkflowRegistry workflowRegistry,
  RestartService restartService,
  ChannelWiring channel,
  SecurityWiring security,
  config_tools.ConfigWriter configWriter,
) => composeServer(
  core: ServerCoreDeps(
    sessions: storage.sessions,
    messages: storage.messages,
    worker: harness.primaryHarness,
    dataDir: ctx.dataDir,
    staticDir: ctx.resolvedAssets.staticDir,
    assetSource: ctx.resolvedAssets.source,
    authEnabled: harness.authEnabled,
    gatewayToken: harness.resolvedGatewayToken,
    runtimeConfig: scheduling.runtimeConfig,
    kvService: storage.kvService,
    configWriter: configWriter,
    config: config,
    configNotifier: ctx.configNotifier,
    restartService: restartService,
    healthService: harness.healthService,
    tokenService: harness.tokenService,
    resetService: harness.resetService,
    redactor: ctx.messageRedactor,
    guardChain: security.guardChain,
    auditLogger: security.auditLogger,
    mcpToolCanonicals: harness.ownMcpToolCanonicals,
    webhookSecret: channel.webhookSecret,
    resultTrimmer: harness.resultTrimmer,
  ),
  turn: ServerTurnDeps(turns: ctx._serverTurns, executions: harness.executions),
  channels: ServerChannelDeps(
    channelManager: channel.channelManager,
    whatsAppChannel: channel.whatsAppChannel,
    signalChannel: channel.signalChannel,
    googleChatWebhookHandler: channel.googleChatWebhookHandler,
    spaceEventsWiring: channel.spaceEventsWiring,
    threadBindingStore: channel.threadBindingStore,
  ),
  tasks: ServerTaskDeps(
    projectService: project.projectService,
    goalService: storage.goalService,
    taskService: storage.taskService,
    taskReviewService: task.taskReviewService,
    worktreeManager: task.worktreeManager,
    taskFileGuard: task.taskFileGuard,
    runnerObserver: task.runnerObserver,
    mergeExecutor: task.mergeExecutor,
    mergeStrategy: config.tasks.worktreeMergeStrategy,
    baseRef: config.tasks.worktreeBaseRef,
    traceService: storage.traceService,
    taskEventService: storage.taskEventService,
    executionDrainer: task.drainExecutions,
    eventBus: ctx.eventBus,
  ),
  observability: ServerObservabilityDeps(
    eventBus: ctx.eventBus,
    sseBroadcast: harness.sseBroadcast,
    providerStatus: providerStatus,
    memoryFile: storage.memoryFile,
    memoryStatusService: scheduling.memoryStatusService,
    memoryPruner: scheduling.memoryPruner,
    memoryService: storage.memory,
    searchBackend: storage.searchBackend,
    memoryCorpus: storage.memoryCorpus,
    scheduleService: scheduling.scheduleService,
    gitSync: scheduling.gitSync,
  ),
  web: ServerWebDeps(
    workflowService: workflowService,
    workflowDefinitionSource: workflowRegistry,
    kgService: storage.kg,
    contentGuardApiKeyConfigured:
        config.security.contentGuardClassifier == 'claude_binary' ||
        (Platform.environment['ANTHROPIC_API_KEY']?.isNotEmpty ?? false),
    contentGuardFailOpen: security.contentGuardFailOpen,
    schedulingJobs: scheduling.displayJobs,
    systemJobNames: scheduling.systemJobNames,
  ),
);
