#!/usr/bin/env dart

import 'dart:collection';
import 'dart:convert';
import 'dart:io';

const _generatedHeader = '// GENERATED by dev/tools/embed_assets.dart – do not edit; regenerate instead.';
const _base64ChunkLength = 88;
const _binaryAssetExtensions = <String>{'.png'};

void main() {
  try {
    generateEmbeddedAssets(_repoRoot());
  } on FileSystemException catch (error) {
    stderr.writeln('embed-assets: ${error.message}: ${error.path}');
    exitCode = 1;
  } on StateError catch (error) {
    stderr.writeln('embed-assets: ${error.message}');
    exitCode = 1;
  } on FormatException catch (error) {
    stderr.writeln('embed-assets: ${error.message}');
    exitCode = 1;
  }
}

void generateEmbeddedAssets(String repoRoot, {void Function(String message)? log}) {
  final logger = log ?? stdout.writeln;
  final bundles = <_AssetBundle>[
    _AssetBundle(
      packageName: 'dartclaw_server',
      variableName: 'embeddedServerAssets',
      binaryVariableName: 'embeddedServerBinaryAssets',
      outputPath: 'packages/dartclaw_server/lib/src/generated/embedded_assets.g.dart',
      roots: const <_AssetRoot>[
        _AssetRoot('packages/dartclaw_server/lib/src/templates', 'templates', excludeDart: true),
        _AssetRoot('packages/dartclaw_server/lib/src/static', 'static'),
      ],
    ),
    _AssetBundle(
      packageName: 'dartclaw_workflow',
      variableName: 'embeddedWorkflowAssets',
      binaryVariableName: 'embeddedWorkflowBinaryAssets',
      outputPath: 'packages/dartclaw_workflow/lib/src/generated/embedded_assets.g.dart',
      roots: const <_AssetRoot>[
        _AssetRoot('packages/dartclaw_workflow/skills', 'skills'),
        _AssetRoot('packages/dartclaw_workflow/lib/src/workflow/definitions', 'workflows'),
      ],
    ),
  ];

  final collected = <(_AssetBundle, _CollectedAssets)>[
    for (final bundle in bundles) (bundle, _collectBundle(repoRoot, bundle)),
  ];

  for (final (bundle, assets) in collected) {
    final output = File('$repoRoot/${bundle.outputPath}')..parent.createSync(recursive: true);
    output.writeAsStringSync(_renderLibrary(bundle.variableName, bundle.binaryVariableName, assets));
    final allAssets = [...assets.text.values, ...assets.binary.values];
    final byteTotal = allAssets.fold<int>(0, (total, bytes) => total + bytes.length);
    logger('${bundle.packageName}: ${allAssets.length} files, $byteTotal bytes');
  }
}

_CollectedAssets _collectBundle(String repoRoot, _AssetBundle bundle) {
  final text = SplayTreeMap<String, List<int>>();
  final binary = SplayTreeMap<String, List<int>>();
  for (final root in bundle.roots) {
    final directory = Directory('$repoRoot/${root.sourcePath}');
    if (!directory.existsSync()) {
      throw FileSystemException('asset root not found', directory.path);
    }
    for (final file in directory.listSync(recursive: true).whereType<File>()) {
      final relative = file.path.substring(directory.path.length + 1).replaceAll('\\', '/');
      if (_isExcluded(relative, excludeDart: root.excludeDart)) {
        continue;
      }
      final bytes = file.readAsBytesSync();
      final key = '${root.keyPrefix}/$relative';
      if (_isBinaryAsset(relative)) {
        binary[key] = bytes;
        continue;
      }
      try {
        utf8.decode(bytes);
      } on FormatException {
        throw FormatException('asset is not valid UTF-8: ${file.path}');
      }
      text[key] = bytes;
    }
  }
  return _CollectedAssets(text: text, binary: binary);
}

bool _isExcluded(String relativePath, {required bool excludeDart}) {
  return relativePath.split('/').any((part) => part.startsWith('.')) || (excludeDart && relativePath.endsWith('.dart'));
}

bool _isBinaryAsset(String relativePath) {
  final dot = relativePath.lastIndexOf('.');
  return dot != -1 && _binaryAssetExtensions.contains(relativePath.substring(dot).toLowerCase());
}

String _renderLibrary(String variableName, String binaryVariableName, _CollectedAssets assets) {
  final output = StringBuffer()
    ..writeln(_generatedHeader)
    ..writeln()
    ..writeln("import 'dart:collection';")
    ..writeln("import 'dart:convert';")
    ..writeln()
    ..writeln('final Map<String, String> $variableName = _EmbeddedAssets(_assetsBase64);')
    ..writeln('final Map<String, List<int>> $binaryVariableName = _EmbeddedBinaryAssets(_binaryAssetsBase64);')
    ..writeln()
    ..writeln('const _assetsBase64 = <String, String>{');

  for (final entry in assets.text.entries) {
    final encoded = base64Encode(entry.value);
    final escapedKey = _escapeDartString(entry.key);
    if (encoded.length <= _base64ChunkLength) {
      final singleLine = "  '$escapedKey': '$encoded',";
      if (singleLine.length <= 120) {
        output.writeln(singleLine);
      } else {
        output
          ..writeln("  '$escapedKey':")
          ..writeln("      '$encoded',");
      }
      continue;
    }
    final chunks = <String>[
      for (var start = 0; start < encoded.length; start += _base64ChunkLength)
        encoded.substring(start, (start + _base64ChunkLength).clamp(0, encoded.length)),
    ];
    output.writeln("  '$escapedKey':");
    for (var index = 0; index < chunks.length; index++) {
      final suffix = index == chunks.length - 1 ? ',' : '';
      output.writeln("      '${chunks[index]}'$suffix");
    }
  }

  output
    ..writeln('};')
    ..writeln();
  final binarySingleLine = assets.binary.length == 1 ? _singleLineEntry(assets.binary.entries.single) : null;
  if (assets.binary.isEmpty) {
    output.writeln('const _binaryAssetsBase64 = <String, String>{};');
  } else if (binarySingleLine != null) {
    output.writeln('const _binaryAssetsBase64 = <String, String>{$binarySingleLine};');
  } else {
    output.writeln('const _binaryAssetsBase64 = <String, String>{');
    _appendEncodedAssets(output, assets.binary);
    output.writeln('};');
  }
  output
    ..writeln()
    ..writeln('final class _EmbeddedAssets extends MapBase<String, String> {')
    ..writeln('  _EmbeddedAssets(this._encoded);')
    ..writeln()
    ..writeln('  final Map<String, String> _encoded;')
    ..writeln('  final Map<String, String> _decoded = <String, String>{};')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  String? operator [](Object? key) {')
    ..writeln('    final encoded = _encoded[key];')
    ..writeln('    if (encoded == null || key is! String) {')
    ..writeln('      return null;')
    ..writeln('    }')
    ..writeln('    return _decoded.putIfAbsent(key, () => utf8.decode(base64Decode(encoded)));')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln(
      "  void operator []=(String key, String value) => throw UnsupportedError('Embedded assets are read-only.');",
    )
    ..writeln()
    ..writeln('  @override')
    ..writeln("  void clear() => throw UnsupportedError('Embedded assets are read-only.');")
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Iterable<String> get keys => _encoded.keys;')
    ..writeln()
    ..writeln('  @override')
    ..writeln("  String? remove(Object? key) => throw UnsupportedError('Embedded assets are read-only.');")
    ..writeln('}')
    ..writeln()
    ..writeln('final class _EmbeddedBinaryAssets extends MapBase<String, List<int>> {')
    ..writeln('  _EmbeddedBinaryAssets(this._encoded);')
    ..writeln()
    ..writeln('  final Map<String, String> _encoded;')
    ..writeln('  final Map<String, List<int>> _decoded = <String, List<int>>{};')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  List<int>? operator [](Object? key) {')
    ..writeln('    final encoded = _encoded[key];')
    ..writeln('    if (encoded == null || key is! String) {')
    ..writeln('      return null;')
    ..writeln('    }')
    ..writeln('    return _decoded.putIfAbsent(key, () => List<int>.unmodifiable(base64Decode(encoded)));')
    ..writeln('  }')
    ..writeln()
    ..writeln('  @override')
    ..writeln(
      "  void operator []=(String key, List<int> value) => throw UnsupportedError('Embedded assets are read-only.');",
    )
    ..writeln()
    ..writeln('  @override')
    ..writeln("  void clear() => throw UnsupportedError('Embedded assets are read-only.');")
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Iterable<String> get keys => _encoded.keys;')
    ..writeln()
    ..writeln('  @override')
    ..writeln("  List<int>? remove(Object? key) => throw UnsupportedError('Embedded assets are read-only.');")
    ..writeln('}');
  return output.toString();
}

String? _singleLineEntry(MapEntry<String, List<int>> entry) {
  final rendered = "'${_escapeDartString(entry.key)}': '${base64Encode(entry.value)}'";
  return rendered.length <= 72 ? rendered : null;
}

void _appendEncodedAssets(StringBuffer output, SplayTreeMap<String, List<int>> assets) {
  for (final entry in assets.entries) {
    final encoded = base64Encode(entry.value);
    final escapedKey = _escapeDartString(entry.key);
    if (encoded.length <= _base64ChunkLength) {
      final singleLine = "  '$escapedKey': '$encoded',";
      if (singleLine.length <= 120) {
        output.writeln(singleLine);
      } else {
        output
          ..writeln("  '$escapedKey':")
          ..writeln("      '$encoded',");
      }
      continue;
    }
    final chunks = <String>[
      for (var start = 0; start < encoded.length; start += _base64ChunkLength)
        encoded.substring(start, (start + _base64ChunkLength).clamp(0, encoded.length)),
    ];
    output.writeln("  '$escapedKey':");
    for (var index = 0; index < chunks.length; index++) {
      final suffix = index == chunks.length - 1 ? ',' : '';
      output.writeln("      '${chunks[index]}'$suffix");
    }
  }
}

String _escapeDartString(String value) => value.replaceAll('\\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$');

String _repoRoot() {
  var directory = File(Platform.script.toFilePath()).parent;
  while (true) {
    if (File('${directory.path}/pubspec.yaml').existsSync() && Directory('${directory.path}/packages').existsSync()) {
      return directory.path;
    }
    final parent = directory.parent;
    if (parent.path == directory.path) {
      throw StateError('repo root not found');
    }
    directory = parent;
  }
}

final class _AssetBundle {
  const _AssetBundle({
    required this.packageName,
    required this.variableName,
    required this.binaryVariableName,
    required this.outputPath,
    required this.roots,
  });

  final String packageName;
  final String variableName;
  final String binaryVariableName;
  final String outputPath;
  final List<_AssetRoot> roots;
}

final class _CollectedAssets {
  const _CollectedAssets({required this.text, required this.binary});

  final SplayTreeMap<String, List<int>> text;
  final SplayTreeMap<String, List<int>> binary;
}

final class _AssetRoot {
  const _AssetRoot(this.sourcePath, this.keyPrefix, {this.excludeDart = false});

  final String sourcePath;
  final String keyPrefix;
  final bool excludeDart;
}
