import 'dart:io';

import 'package:test/test.dart';

import '../../../../dev/tools/embed_assets.dart';

const _longEmptyAssetName =
    'empty-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt';

void main() {
  late Directory tempDir;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('dartclaw_embed_assets_');
    _writeFixture(tempDir.path);
  });

  tearDown(() => tempDir.deleteSync(recursive: true));

  test('S01/S02 generator output is complete, filtered, and deterministic', () {
    final summaries = <String>[];

    generateEmbeddedAssets(tempDir.path, log: summaries.add);
    final serverOutput = _serverOutput(tempDir.path).readAsStringSync();
    final workflowOutput = _workflowOutput(tempDir.path).readAsStringSync();

    generateEmbeddedAssets(tempDir.path, log: summaries.add);

    expect(_serverOutput(tempDir.path).readAsStringSync(), serverOutput);
    expect(_workflowOutput(tempDir.path).readAsStringSync(), workflowOutput);
    expect(
      serverOutput,
      startsWith('// GENERATED by dev/tools/embed_assets.dart – do not edit; regenerate instead.\n'),
    );
    expect(
      workflowOutput,
      startsWith('// GENERATED by dev/tools/embed_assets.dart – do not edit; regenerate instead.\n'),
    );
    expect(serverOutput, contains("'templates/page.html'"));
    expect(serverOutput, contains("'static/controllers/index.js'"));
    expect(serverOutput, contains("'static/empty.txt': '',"));
    expect(serverOutput, contains("'static/$_longEmptyAssetName':\n      '',"));
    expect(serverOutput, isNot(contains('page.dart')));
    expect(serverOutput, isNot(contains('.DS_Store')));
    expect(serverOutput, isNot(contains('.cache')));
    expect(serverOutput, isNot(contains('.nested.swp')));
    expect(workflowOutput, contains("'skills/example/SKILL.md'"));
    expect(workflowOutput, contains("'workflows/example.yaml'"));
    expect(workflowOutput, isNot(contains('.example.yaml.swp')));
    expect(
      summaries,
      containsAll(<String>['dartclaw_server: 4 files, 41 bytes', 'dartclaw_workflow: 2 files, 30 bytes']),
    );
    _expectFormatClean(<File>[_serverOutput(tempDir.path), _workflowOutput(tempDir.path)]);
  });

  test('rejects malformed UTF-8 before writing any generated output', () {
    final invalid = File('${tempDir.path}/packages/dartclaw_server/lib/src/static/invalid.txt')
      ..writeAsBytesSync(<int>[0xff]);
    final summaries = <String>[];

    expect(
      () => generateEmbeddedAssets(tempDir.path, log: summaries.add),
      throwsA(isA<FormatException>().having((error) => error.message, 'message', contains(invalid.path))),
    );
    expect(summaries, isEmpty);
    expect(_serverOutput(tempDir.path).existsSync(), isFalse);
    expect(_workflowOutput(tempDir.path).existsSync(), isFalse);
  });
}

void _writeFixture(String root) {
  File('$root/packages/dartclaw_server/lib/src/templates/page.html')
    ..createSync(recursive: true)
    ..writeAsStringSync('<main>fixture</main>\n');
  File('$root/packages/dartclaw_server/lib/src/templates/page.dart').writeAsStringSync('const compiled = true;\n');
  File('$root/packages/dartclaw_server/lib/src/templates/.DS_Store').writeAsStringSync('noise');
  File('$root/packages/dartclaw_server/lib/src/static/controllers/index.js')
    ..createSync(recursive: true)
    ..writeAsStringSync('export const x = 1;\n');
  File('$root/packages/dartclaw_server/lib/src/static/empty.txt').createSync();
  File('$root/packages/dartclaw_server/lib/src/static/$_longEmptyAssetName').createSync();
  File('$root/packages/dartclaw_server/lib/src/static/.cache/ignored.txt')
    ..createSync(recursive: true)
    ..writeAsStringSync('noise');
  File('$root/packages/dartclaw_server/lib/src/static/controllers/.nested.swp').writeAsStringSync('noise');
  File('$root/packages/dartclaw_workflow/skills/example/SKILL.md')
    ..createSync(recursive: true)
    ..writeAsStringSync('# Fixture skill\n');
  File('$root/packages/dartclaw_workflow/lib/src/workflow/definitions/example.yaml')
    ..createSync(recursive: true)
    ..writeAsStringSync('name: fixture\n');
  File('$root/packages/dartclaw_workflow/lib/src/workflow/definitions/.example.yaml.swp').writeAsStringSync('noise');
}

File _serverOutput(String root) => File('$root/packages/dartclaw_server/lib/src/generated/embedded_assets.g.dart');

File _workflowOutput(String root) => File('$root/packages/dartclaw_workflow/lib/src/generated/embedded_assets.g.dart');

void _expectFormatClean(List<File> files) {
  final result = Process.runSync(Platform.resolvedExecutable, <String>[
    'format',
    '--line-length=120',
    '--output=none',
    '--set-exit-if-changed',
    ...files.map((file) => file.path),
  ]);
  expect(result.exitCode, 0, reason: '${result.stdout}${result.stderr}');
}
